package com.example.demo.procurement.domain.model.enums;

public enum POStatus {
    UNPAID,RECIEVED,PAID,PENDING, OPEN, REJECTED,PENDING_EXTENSION, CLOSED, CANCELLED, DISPATCHED, DELIVERED, REJECTED_BY_CUSTOMER, RETURNED, INVOICED
}
